
# Radar system parameters (corrected)
ADC_SAMPLE_RATE = 1e6  # 1 MHz (but under-sampled)
CHIRP_DURATION = 350e-6  # 350 μs
SAMPLES_PER_CHIRP = 128  # 128 samples
CHIRPS_PER_FRAME = 32  # 32 chirps
BANDWIDTH = 4e9  # 4 GHz
CARRIER_FREQ = 60e9  # 60 GHz
FRAME_RATE = 10  # 10 FPS
SPEED_OF_LIGHT = 3e8  # m/s

# Correctly derived parameters
ACTUAL_SAMPLE_RATE = SAMPLES_PER_CHIRP / CHIRP_DURATION  # ~365.7 kHz
RANGE_RESOLUTION = SPEED_OF_LIGHT / (2 * BANDWIDTH)  # 3.75 cm
MAX_RANGE = (SPEED_OF_LIGHT * CHIRP_DURATION) / 2  # 52.5km theoretical, but:
MAX_UNAMBIGUOUS_RANGE = (SPEED_OF_LIGHT * SAMPLES_PER_CHIRP) / (4 * BANDWIDTH)  # 2.4m (corrected)
FRAME_DURATION = CHIRPS_PER_FRAME * CHIRP_DURATION  # 11.2 ms
DOPPLER_RESOLUTION = SPEED_OF_LIGHT / (2 * CARRIER_FREQ * FRAME_DURATION)  # 0.223 m/s
MAX_VELOCITY = SPEED_OF_LIGHT / (4 * CARRIER_FREQ * CHIRP_DURATION)  # 3.57 m/s
